### ISSUE TITLE
Wiki「認証について」の改善1

### ISSUE THREAD

**Issue by bigen1925** [sayanok/zetter#16]
```diff
- ## 大まかな流れ
- userNameとpasswordを用いてログインする
- ログインに用いられたuserNameとpasswordがDBに登録しているものと一致した場合、下記の流れで認証する
- 
- ### 1. ログイン時にtokenを発行
- ログインに用いられたuserName及びpasswordを持つユーザーがDBに登録されていることが確認できたら、tokenを発行する
- 詳細はtokenの発行方法参照
- 
- ### 2.発行したtokenをHeaderのAuthorizationに登録する
- 
- ### 3.ユーザーがアクションを実行する際、authメソッドを用いて認証する
- RequestHeaderのAuthorizationに登録されているtokenを用いて認証を行う
- 詳細は認証について参照
+ ## APIサーバーの認証の大まかな流れ
+ フロントエンドは、認証が必要なAPIのエンドポイントへリクエストを送信する際に、以下の流れにのっとる必要がある
+ 
+ ### 1. ログインリクエスト
+ フロントエンドは、usernameとpasswordを`/login`へ送る
+ 
+ ### 2. tokenの発行
+  APIサーバーは、userNameとpasswordがDBに登録しているものと一致することを確認した後、tokenを発行する
+ 詳細はtokenの発行方法参照
+ 
+ ### 3. 認証付きリクエスト
+ フロントエンドは、認証が必要なエンドポイントへリクエストをする際に、2で発行されたtokenをAuthorizationヘッダに`Bearer <token>`の形式で付与して送信する
+ 
+ ### 4. 認証
+ APIサーバーは、認証が必要なエンドポイントではミドルウェアで認証を行う
+ 詳細は認証について参照
```
### 特に重要なポイント

処理や動作を書く場合には、どのコンポーネントがそれを行う必要があるのかをある程度書くと読みやすいが、細かすぎてもどこの話をしているか分かりにくい。例えば今回でいうと、`authメソッド`のような詳細なメソッド名の前に、そもそもフロントエンドがやるのか、APIサーバーがやるのか、というところをはっきりさせておくと読みやすい。必要に応じて、関数単位で表現でしてもよいが、あまり重要でない場合が多い。

### 重要ではないが、読みやすくなる工夫
> - userNameとpasswordを用いてログインする
- ログインに用いられたuserNameとpasswordがDBに登録しているものと一致した場合、下記の流れで認証する

の部分も認証の流れの一部なので、組み込んでしまったほうが読みやすい

### どうでもいいこと
「ヘッダーに登録」とはあまり言わない
「登録」というと、データベースやファイルのように長期的にデータを保管しておくところへの保存のイメージが強い
「ヘッダーに付与」とか「ヘッダーに乗せて送る」とかぐらいの表現が多い

-------------

```diff
- tokenとtoken発行時に用いたシークレットキーを用いてverify signatureが改ざんされていないことを検証する
+  tokenとtoken発行時に用いたシークレットキーを用いてhashを計算し、verify signatureと比較することでtoken本文が改ざんされていないこと、及び発行者がAPIサーバー自身であることを検証する
```
### 重要なこと
`verify signature`が改ざんされていないことを確認するのではなく、**token本体**が改ざんされていないことを確認する

### 高度なので今は理解していなくてもよいこと
token本体が改ざんされていないことを確認すると同時に、発行者がAPIサーバー自身であることも確認している

例えば、APIサーバーではない悪意ある第三者が適当に作ったtoken（改ざんはされていない）などが弾かれるようになっている

**Comment by sayanok** [comment]
https://github.com/sayanok/zetter/wiki/%E8%AA%8D%E8%A8%BC%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
修正したよ
あと、コメント理解したと思う

**Comment by bigen1925** [comment]
良いと思います
